// export const employees = [
//     {
//         date: "2025-01-15",
//         eCode: "EMP001",
//         department: "Sales",
//         firstLocation: "Kolkata",
//         transferredFrom: "-",
//         currentLocation: "Kolkata",
//         state: "West Bengal",
//         payroll: "On-Roll",
//         dateOfJoinning: "2023-06-12",
//         status: "Active",
//         gender: "Male",
//         dob: "1998-07-12",
//         bankName: "HDFC Bank",
//         bankAccount: "123456789012",
//         ifscCode: "HDFC0001234",
//         pfApplication: "Yes",
//         uanNo: "101234567890",
//         pfNo: "WB/12345/67890",
//         esicIpCode: "1234567890",
//         aadhaarNo: "567812349012",
//         pan: "ABCPD1234K",
//         fathersName: "Rajesh Sharma",
//         mobileNo: "9876543210",
//         officialEmail: "aarav.sharma@company.in",
//         email: "aarav98@gmail.com",
//         monthlyCTC: 35000,
//     },
//     {
//         date: "2025-01-16",
//         eCode: "EMP002",
//         department: "Operations",
//         firstLocation: "Delhi",
//         transferredFrom: "-",
//         currentLocation: "Delhi",
//         state: "Delhi",
//         payroll: "Off-Roll",
//         dateOfJoinning: "2024-02-18",
//         status: "Active",
//         gender: "Female",
//         dob: "1996-09-05",
//         bankName: "State Bank of India",
//         bankAccount: "987654321098",
//         ifscCode: "SBIN0000456",
//         pfApplication: "No",
//         uanNo: "-",
//         pfNo: "-",
//         esicIpCode: "9988776655",
//         aadhaarNo: "901256781234",
//         pan: "DFGHT5678P",
//         fathersName: "Manoj Verma",
//         mobileNo: "9123456780",
//         officialEmail: "priya.verma@company.in",
//         email: "priyav@gmail.com",
//         monthlyCTC: 28000,
//     },
//     {
//         date: "2025-01-18",
//         eCode: "EMP003",
//         department: "Finance",
//         firstLocation: "Mumbai",
//         transferredFrom: "Pune",
//         currentLocation: "Mumbai",
//         state: "Maharashtra",
//         payroll: "On-Roll",
//         dateOfJoinning: "2022-10-10",
//         status: "Transferred",
//         gender: "Male",
//         dob: "1995-03-22",
//         bankName: "ICICI Bank",
//         bankAccount: "223344556677",
//         ifscCode: "ICIC0000789",
//         pfApplication: "Yes",
//         uanNo: "102938475610",
//         pfNo: "MH/98765/43210",
//         esicIpCode: "5566778899",
//         aadhaarNo: "345678901256",
//         pan: "GHYTR2345L",
//         fathersName: "Harjeet Singh",
//         mobileNo: "9090909090",
//         officialEmail: "rohan.singh@company.in",
//         email: "rohanx@gmail.com",
//         monthlyCTC: 42000,
//     },
//     {
//         date: "2025-01-20",
//         eCode: "EMP004",
//         department: "HR",
//         firstLocation: "Chennai",
//         transferredFrom: "-",
//         currentLocation: "Chennai",
//         state: "Tamil Nadu",
//         payroll: "On-Roll",
//         dateOfJoinning: "2023-01-25",
//         status: "Active",
//         gender: "Female",
//         dob: "1999-12-10",
//         bankName: "Kotak Mahindra Bank",
//         bankAccount: "778899001122",
//         ifscCode: "KKBK0000678",
//         pfApplication: "No",
//         uanNo: "-",
//         pfNo: "-",
//         esicIpCode: "1100220033",
//         aadhaarNo: "789012345612",
//         pan: "JHGTY5678M",
//         fathersName: "Mahesh Patel",
//         mobileNo: "9811223344",
//         officialEmail: "sneha.patel@company.in",
//         email: "snehapatel@gmail.com",
//         monthlyCTC: 30000,
//     },
//     {
//         date: "2025-01-22",
//         eCode: "EMP005",
//         department: "IT",
//         firstLocation: "Hyderabad",
//         transferredFrom: "-",
//         currentLocation: "Hyderabad",
//         state: "Telangana",
//         payroll: "Off-Roll",
//         dateOfJoinning: "2024-04-01",
//         status: "Active",
//         gender: "Male",
//         dob: "1993-06-30",
//         bankName: "Axis Bank",
//         bankAccount: "665544332211",
//         ifscCode: "UTIB0000345",
//         pfApplication: "Yes",
//         uanNo: "123450987612",
//         pfNo: "TS/44556/77889",
//         esicIpCode: "3344556677",
//         aadhaarNo: "456789012345",
//         pan: "KLMNO1234Q",
//         fathersName: "Suresh Rao",
//         mobileNo: "9845123456",
//         officialEmail: "vikram.rao@company.in",
//         email: "vikramr93@gmail.com",
//         monthlyCTC: 50000,
//     },
//     {
//         date: "2025-01-22",
//         eCode: "EMP005",
//         department: "IT",
//         firstLocation: "Hyderabad",
//         transferredFrom: "-",
//         currentLocation: "Hyderabad",
//         state: "Telangana",
//         payroll: "Off-Roll",
//         dateOfJoinning: "2024-04-01",
//         status: "Active",
//         gender: "Male",
//         dob: "1993-06-30",
//         bankName: "Axis Bank",
//         bankAccount: "665544332211",
//         ifscCode: "UTIB0000345",
//         pfApplication: "Yes",
//         uanNo: "123450987612",
//         pfNo: "TS/44556/77889",
//         esicIpCode: "3344556677",
//         aadhaarNo: "456789012345",
//         pan: "KLMNO1234Q",
//         fathersName: "Suresh Rao",
//         mobileNo: "9845123456",
//         officialEmail: "vikram.rao@company.in",
//         email: "vikramr93@gmail.com",
//         monthlyCTC: 50000,
//     },
//     {
//         date: "2025-01-22",
//         eCode: "EMP005",
//         department: "IT",
//         firstLocation: "Hyderabad",
//         transferredFrom: "-",
//         currentLocation: "Hyderabad",
//         state: "Telangana",
//         payroll: "Off-Roll",
//         dateOfJoinning: "2024-04-01",
//         status: "Active",
//         gender: "Male",
//         dob: "1993-06-30",
//         bankName: "Axis Bank",
//         bankAccount: "665544332211",
//         ifscCode: "UTIB0000345",
//         pfApplication: "Yes",
//         uanNo: "123450987612",
//         pfNo: "TS/44556/77889",
//         esicIpCode: "3344556677",
//         aadhaarNo: "456789012345",
//         pan: "KLMNO1234Q",
//         fathersName: "Suresh Rao",
//         mobileNo: "9845123456",
//         officialEmail: "vikram.rao@company.in",
//         email: "vikramr93@gmail.com",
//         monthlyCTC: 50000,
//     }
// ];

// export const techIssues = [
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9876543210",
//         issueDescription: "Unable to login. Showing 'Invalid Credentials' even though password is correct.",
//         screenshot: "login_error_01.png",
//         status: "Approved",
//         approvedBy: "Navis",
//         confirmedBy: "Surjeet"

//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9123456780",
//         issueDescription: "Employee details not updating after editing. Data remains the same after refresh.",
//         screenshot: "edit_issue.jpg",
//         reason: "reason xyzksjjs jsjjsjsjs",
//         status: "Rejected",
//         approvedBy: "Pratik",
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9087654321",
//         issueDescription: "Portal extremely slow during peak hours. Taking 20+ seconds to load dashboard.",
//         screenshot: null,
//         status: "Approved",
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9812345678",
//         issueDescription: "Can't generate PDF report. Throws 'Server error 500'.",
//         screenshot: "pdf_crash.png",
//         status: "Approved",
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9900112233",
//         issueDescription: "Tech issue form is submitting twice, generating duplicate tickets.",
//         screenshot: "duplicate_ticket.png",
//         reason: "reason xyzksjjs jsjjsjsjs",
//         status: "Rejected",
//         approvedBy: "Pratik",
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9797979797",
//         issueDescription: "Unable to upload employee photo. Says file too large even for 200KB image.",
//         screenshot: "upload_fail.jpg",
//         reason: "reason xyzksjjs jsjjsjsjs",
//         status: "Rejected",
//         approvedBy: "Pratik",
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9001122334",
//         issueDescription: "Not receiving OTP on mobile during password reset.",
//         screenshot: null
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "8899001122",
//         issueDescription: "Table headers overlapping when scrolling horizontally on small screens.",
//         screenshot: "ui_glitch.png"
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9345678901",
//         issueDescription: "Filters not working. Search by ECode returns empty although data exists.",
//         screenshot: null
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9776655443",
//         issueDescription: "Export to Excel downloading corrupted file. Cannot be opened.",
//         screenshot: "excel_error.jpg"
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9898981212",
//         issueDescription: "Getting logged out automatically every 2 minutes.",
//         screenshot: null
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9000001112",
//         issueDescription: "Employee transfer form not loading dropdown data for centers.",
//         screenshot: "dropdown_fail.png"
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "7778889990",
//         issueDescription: "Official email field validation not working. Accepts wrong formats.",
//         screenshot: null
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9301234567",
//         issueDescription: "Can't delete employee record. Delete button does nothing.",
//         screenshot: "delete_issue.png"
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9012345678",
//         issueDescription: "Pagination stuck on page 1. Can't navigate to next pages.",
//         screenshot: "pagination_bug.jpg"
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "8887776665",
//         issueDescription: "Approval flow page blank for some employees.",
//         screenshot: null
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9009900990",
//         issueDescription: "Mobile UI broken on iPhone. Cards overlap on top of each other.",
//         screenshot: "mobile_bug.png"
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9333222211",
//         issueDescription: "Upload limit says 1GB but rejects files larger than 5MB.",
//         screenshot: "upload_limit_issue.jpg"
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9900887766",
//         issueDescription: "Center dropdown showing old inactive centers as well.",
//         screenshot: null
//     },
//     {
//         name: "Test xyz",
//         center: "Pune HWH",
//         contactNo: "9811122233",
//         issueDescription: "Tech issue form not showing file preview after uploading.",
//         screenshot: "file_preview_error.png"
//     }
// ];

// export const salaryAdvances = [
//     {
//         center: "Pune HWH",
//         eCode: "EMP001",
//         name: "Aarav Sharma",
//         employeeName: "test xyz",
//         amount: 12000,
//         email: "aarav.sharma@company.in",
//         date: "25 Nov 2025, 12:25 PM",
//         status: "Approved",
//         paymentType: "CASH"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP002",
//         name: "Priya Verma",
//         amount: 8000,
//         employeeName: "test xyz",
//         email: "priya.verma@company.in",
//         date: "25 Nov 2025, 12:25 PM",
//         status: "Approved",
//         paymentType: "CENTRALLY"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP003",
//         name: "Rohan Singh",
//         employeeName: "test xyz",

//         amount: 15000,
//         email: "rohan.singh@company.in",
//         date: "25 Nov 2025, 12:25 PM",
//         paymentType: "CENTRALLY",
//         status: "Approved",
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP004",
//         name: "Sneha Patel",
//         employeeName: "test xyz",

//         amount: 5000,
//         email: "sneha.patel@company.in",
//         date: "25 Nov 2025, 12:25 PM",
//         paymentType: "CASH",
//         status: "Approved",
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP005",
//         name: "Vikram Rao",
//         employeeName: "test xyz",

//         amount: 18000,
//         email: "vikram.rao@company.in",
//         date: "25 Nov 2025, 12:25 PM",
//         paymentType: "CASH",
//         status: "Approved",
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP006",
//         name: "Ishita Das",
//         employeeName: "test xyz",
//         amount: 7000,
//         email: "ishita.das@company.in",
//         date: "25 Nov 2025, 12:25 PM",
//         paymentType: "CASH",
//         status: "Approved",
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP007",
//         employeeName: "test xyz",

//         name: "Kunal Mehta",
//         amount: 22000,
//         email: "kunal.mehta@company.in",
//         date: "25 Nov 2025, 12:25 PM",
//         status: "Rejected",
//         reason: "xyz reason"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP008",
//         employeeName: "test xyz",
//         name: "Simran Kaur",
//         amount: 9500,
//         email: "simran.kaur@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         employeeName: "test xyz",
//         eCode: "EMP009",
//         name: "Aditya Roy",
//         amount: 14000,
//         email: "aditya.roy@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP010",
//         name: "Megha Nair",
//         amount: 6000,
//         email: "megha.nair@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP011",
//         name: "Rahul Bose",
//         employeeName: "test xyz",
//         amount: 20000,
//         email: "rahul.bose@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP012",
//         name: "Tanya Kapoor",
//         amount: 3000,
//         email: "tanya.kapoor@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP013",
//         name: "Harsh Vardhan",
//         amount: 25000,
//         email: "harsh.vardhan@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP014",
//         name: "Nidhi Kumari",
//         amount: 11000,
//         email: "nidhi.kumari@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP015",
//         name: "Saurabh Jain",
//         amount: 13000,
//         email: "saurabh.jain@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP016",
//         name: "Muskan Gupta",
//         amount: 4000,
//         email: "muskan.gupta@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP017",
//         name: "Jay Patel",
//         amount: 19000,
//         email: "jay.patel@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP018",
//         name: "Ananya Mukherjee",
//         amount: 16000,
//         email: "ananya.mukherjee@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP019",
//         name: "Deepak Malhotra",
//         amount: 9000,
//         email: "deepak.malhotra@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     },
//     {
//         center: "Pune HWH",
//         eCode: "EMP020",
//         name: "Ritika Sharma",
//         amount: 10000,
//         email: "ritika.sharma@company.in",
//         date: "25 Nov 2025, 12:25 PM"
//     }
// ];


// export const exitEmployees = [
//     {
//         center: "Pune HWH",
//         name: "Aarav Sharma",
//         eCode: "EMP001",
//         employeeName: "test xyz",
//         date: "25 Nov 2025, 12:25 PM",
//         reason: "Self resigning",
//         lastWorkingDay: "10 Jan 2025",
//         email: "aarav.sharma@company.in",
//         approvedBy: "Shree",
//         status: "Approved",
//         approvedDate: "12 Jan 2025"
//     },
//     {
//         center: "Pune HWH",
//         name: "Priya Verma",
//         eCode: "EMP002",
//         status: "Approved",
//         date: "25 Nov 2025, 12:25 PM",
//         employeeName: "test xyz",
//         reason: "Performance Issue",
//         lastWorkingDay: "08 Jan 2025",
//         email: "priya.verma@company.in",
//         approvedBy: "Navis",
//         approvedDate: "09 Jan 2025"
//     },
//     {
//         center: "Mumbai Central",
//         name: "Rohan Singh",
//         eCode: "EMP003",
//         date: "25 Nov 2025, 12:25 PM",
//         reason: "Behaviour Issue",
//         employeeName: "test xyz",
//         lastWorkingDay: "22 Jan 2025",
//         status: "Approved",
//         email: "rohan.singh@company.in",
//         approvedBy: "Pratik",
//         approvedDate: "23 Jan 2025"
//     },
//     {
//         center: "Delhi HQ",
//         name: "Sneha Patel",
//         eCode: "EMP004",
//         status: "Approved",

//         date: "25 Nov 2025, 12:25 PM",
//         reason: "Self resigning",
//         employeeName: "test xyz",
//         lastWorkingDay: "18 Jan 2025",
//         email: "sneha.patel@company.in",
//         approvedBy: "Shree",
//         approvedDate: "19 Jan 2025"
//     },
//     {
//         center: "Hyderabad West",
//         name: "Vikram Rao",
//         eCode: "EMP005",
//         status: "Approved",

//         date: "25 Nov 2025, 12:25 PM",
//         reason: "Ethical Issue",
//         employeeName: "test xyz",

//         lastWorkingDay: "25 Jan 2025",
//         email: "vikram.rao@company.in",
//         approvedBy: "Regional Head",
//         approvedDate: "27 Jan 2025"
//     },
//     {
//         center: "Chennai South",
//         name: "Ishita Das",
//         status: "Approved",

//         eCode: "EMP006",
//         reason: "Self resigning",
//         employeeName: "test xyz",

//         lastWorkingDay: "16 Jan 2025",
//         email: "ishita.das@company.in",
//         approvedBy: "Hemant",
//         approvedDate: "17 Jan 2025"
//     },
//     {
//         center: "Kolkata North",
//         name: "Kunal Mehta",
//         eCode: "EMP007",
//         status: "Approved",

//         reason: "Performance Issue",
//         employeeName: "test xyz",

//         lastWorkingDay: "07 Jan 2025",
//         email: "kunal.mehta@company.in",
//         approvedBy: "Surjeet",
//         approvedDate: "08 Jan 2025"
//     },
//     {
//         center: "Pune HWH",
//         name: "Simran Kaur",
//         status: "Approved",

//         eCode: "EMP008",
//         reason: "Self resigning",
//         employeeName: "test xyz",
//         lastWorkingDay: "03 Jan 2025",
//         email: "simran.kaur@company.in",
//         approvedBy: "Shree",
//         approvedDate: "04 Jan 2025"
//     },
//     {
//         center: "Delhi HQ",
//         name: "Aditya Roy",
//         eCode: "EMP009",
//         status: "Approved",

//         reason: "Behaviour Issue",
//         employeeName: "test xyz",

//         lastWorkingDay: "14 Jan 2025",
//         email: "aditya.roy@company.in",
//         approvedBy: "HR Manager",
//         approvedDate: "15 Jan 2025"
//     },
//     {
//         center: "Mumbai Central",
//         name: "Megha Nair",
//         eCode: "EMP010",
//         reason: "Self resigning",
//         employeeName: "test xyz",

//         lastWorkingDay: "29 Jan 2025",
//         email: "megha.nair@company.in",
//         approvedBy: "Regional Head",
//         approvedDate: "30 Jan 2025"
//     },
//     {
//         center: "Hyderabad West",
//         name: "Rahul Bose",
//         eCode: "EMP011",
//         reason: "Ethical Issue",
//         employeeName: "test xyz",

//         lastWorkingDay: "05 Jan 2025",
//         email: "rahul.bose@company.in",
//         approvedBy: "Hemant",
//         approvedDate: "06 Jan 2025"
//     },
//     {
//         center: "Chennai South",
//         name: "Tanya Kapoor",
//         eCode: "EMP012",
//         employeeName: "test xyz",
//         reason: "Performance Issue",
//         lastWorkingDay: "11 Jan 2025",
//         email: "tanya.kapoor@company.in",
//         approvedBy: "Surjeet",
//         approvedDate: "12 Jan 2025"
//     },
//     {
//         center: "Pune HWH",
//         name: "Harsh Vardhan",
//         eCode: "EMP013",
//         reason: "Other: Better opportunity",
//         lastWorkingDay: "17 Jan 2025",
//         email: "harsh.vardhan@company.in",
//         approvedBy: "Shree",
//         approvedDate: "18 Jan 2025"
//     },
//     {
//         center: "Kolkata North",
//         name: "Nidhi Kumari",
//         eCode: "EMP014",
//         reason: "Self resigning",
//         lastWorkingDay: "19 Jan 2025",
//         email: "nidhi.kumari@company.in",
//         approvedBy: "HR Manager",
//         approvedDate: "20 Jan 2025"
//     },
//     {
//         center: "Hyderabad West",
//         name: "Saurabh Jain",
//         eCode: "EMP015",
//         reason: "Behaviour Issue",
//         lastWorkingDay: "12 Jan 2025",
//         email: "saurabh.jain@company.in",
//         approvedBy: "Regional Head",
//         approvedDate: "13 Jan 2025"
//     },
//     {
//         center: "Pune HWH",
//         name: "Muskan Gupta",
//         eCode: "EMP016",
//         reason: "Self resigning",
//         lastWorkingDay: "06 Jan 2025",
//         email: "muskan.gupta@company.in",
//         approvedBy: "Shree",
//         approvedDate: "07 Jan 2025"
//     },
//     {
//         center: "Delhi HQ",
//         name: "Jay Patel",
//         eCode: "EMP017",
//         reason: "Performance Issue",
//         lastWorkingDay: "21 Jan 2025",
//         email: "jay.patel@company.in",
//         approvedBy: "Hemant",
//         approvedDate: "22 Jan 2025"
//     },
//     {
//         center: "Chennai South",
//         name: "Ananya Mukherjee",
//         eCode: "EMP018",
//         reason: "Self resigning",
//         lastWorkingDay: "02 Jan 2025",
//         email: "ananya.mukherjee@company.in",
//         approvedBy: "Surjeet",
//         approvedDate: "03 Jan 2025"
//     },
//     {
//         center: "Mumbai Central",
//         name: "Deepak Malhotra",
//         eCode: "EMP019",
//         reason: "Ethical Issue",
//         lastWorkingDay: "28 Jan 2025",
//         email: "deepak.malhotra@company.in",
//         approvedBy: "HR Manager",
//         approvedDate: "29 Jan 2025"
//     },
//     {
//         center: "Pune HWH",
//         name: "Ritika Sharma",
//         eCode: "EMP020",
//         reason: "Self resigning",
//         lastWorkingDay: "09 Jan 2025",
//         email: "ritika.sharma@company.in",
//         approvedBy: "Shree",
//         approvedDate: "10 Jan 2025"
//     }
// ];




