const P = "geriatricFields";

const geriatricConfig = [
  {
    title: "History of Present Illness",
    items: [
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.onsetAgeDate`,
        label: "Age / date at onset of current problem",
        type: "text",
      },
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.modeOfOnset`,
        label: "Mode of onset",
        type: "select",
        options: [
          "Acute (< 1 week)",
          "Subacute (weeks)",
          "Insidious / Gradual (months–years)",
        ],
      },
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.course`,
        label: "Course",
        type: "select",
        options: [
          "Stable",
          "Slowly progressive",
          "Stepwise / fluctuating",
          "Rapidly progressive",
          "Terminal decline",
        ],
      },
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.precipitatingEvent`,
        label: "Precipitating event (if any)",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.chronologicalNarrative`,
        label: "Chronological narrative of current illness",
        type: "textarea",
      },
      {
        kind: "field",
        path: `${P}.cognitiveSymptoms.memoryComplaints`,
        label: "Memory complaints",
        type: "multiselect",
        options: [
          "None",
          "Short-term memory loss",
          "Long-term memory loss",
          "Gets lost in familiar places",
          "Forgets names of family / familiar objects",
          "Repetitive questioning",
        ],
      },
      {
        kind: "field",
        path: `${P}.cognitiveSymptoms.languageCommunication`,
        label: "Language / Communication",
        type: "multiselect",
        options: [
          "Intact",
          "Word-finding difficulty (anomia)",
          "Reduced fluency",
          "Comprehension impaired",
          "Non-verbal only",
          "Mutism",
        ],
      },
      {
        kind: "field",
        path: `${P}.cognitiveSymptoms.executiveVisuospatial`,
        label: "Executive / Visuospatial",
        type: "multiselect",
        options: [
          "Intact",
          "Poor planning / sequencing",
          "Can't manage finances / medications",
          "Gets lost / disoriented",
          "Dressing difficulty (apraxia)",
          "Misidentifies objects / faces (agnosia)",
        ],
      },
      {
        kind: "field",
        path: `${P}.cognitiveSymptoms.orientation`,
        label: "Orientation",
        type: "multiselect",
        options: [
          "Fully oriented",
          "Disoriented to time",
          "Disoriented to place",
          "Disoriented to person",
          "Disoriented to situation",
        ],
      },
      {
        kind: "field",
        path: `${P}.cognitiveSymptoms.timelineOfCognitiveDecline`,
        label: "Timeline of cognitive decline (milestones)",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.bpsd.moodSymptoms`,
        label: "BPSD — mood symptoms",
        type: "multiselect",
        options: [
          "Depression",
          "Apathy / Withdrawal",
          "Anxiety",
          "Euphoria / Disinhibition",
          "Emotional lability",
          "None",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.bpsd.psychoticSymptoms`,
        label: "BPSD — psychotic symptoms",
        type: "multiselect",
        options: [
          "Paranoid delusions",
          "Misidentification syndromes",
          "Hallucinations — visual",
          "Hallucinations — auditory",
          "Other hallucinations",
          "None",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.bpsd.agitationAggression`,
        label: "Agitation / Aggression",
        type: "multiselect",
        options: [
          "Verbal aggression",
          "Physical aggression",
          "Restlessness",
          "Pacing / Wandering",
          "None",
        ],
      },
      {
        kind: "field",
        path: `${P}.bpsd.sleepWakeDisturbance`,
        label: "Sleep–wake cycle disturbance",
        type: "multiselect",
        options: [
          "Day–night reversal",
          "Insomnia",
          "Hypersomnia",
          "Sundowning",
          "None",
        ],
      },
      {
        kind: "field",
        path: `${P}.bpsd.eatingAppetite`,
        label: "Eating / Appetite",
        type: "multiselect",
        options: [
          "Intact",
          "Reduced appetite",
          "Dysphagia — solids",
          "Dysphagia — liquids",
          "Weight loss",
          "Hyperphagia",
          "Pica",
          "None",
        ],
      },
      {
        kind: "field",
        path: `${P}.bpsd.bpsdDetailsImpact`,
        label: "BPSD details / impact on caregiving",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.deliriumScreen.acuteChangeFromBaseline`,
        label: "Acute change from baseline?",
        type: "yesno",
      },
      {
        kind: "field",
        path: `${P}.deliriumScreen.featuresOfDelirium`,
        label: "Features of delirium",
        type: "multiselect",
        options: [
          "Fluctuating consciousness",
          "Inattention",
          "Disorganised thinking",
          "Perceptual disturbances",
          "Psychomotor changes",
          "None identified",
        ],
      },
      {
        kind: "field",
        path: `${P}.deliriumScreen.likelyAetiology`,
        label: "Likely delirium aetiology (if applicable)",
        type: "select",
        options: [
          "Infection / Sepsis",
          "Medication / Polypharmacy",
          "Metabolic",
          "Pain / Urinary retention",
          "Constipation",
          "Dehydration",
          "Post-operative",
          "Unknown",
          "N/A",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.psychiatricSymptomDomains.depressiveSymptoms`,
        label: "Depressive symptoms",
        type: "multiselect",
        options: [
          "Low mood",
          "Anhedonia",
          "Hopelessness",
          "Worthlessness",
          "Suicidal ideation",
          "Psychomotor change",
          "None",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.psychiatricSymptomDomains.anxietySymptoms`,
        label: "Anxiety symptoms",
        type: "multiselect",
        options: [
          "Generalised worry",
          "Panic attacks",
          "Specific phobias",
          "Health anxiety",
          "Separation anxiety from caregiver",
          "None",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.pastPsychiatricHistory.lifetimeDiagnoses`,
        label: "Lifetime psychiatric diagnoses",
        type: "multiselect",
        options: [
          "None",
          "Depression",
          "Anxiety / GAD",
          "Bipolar disorder",
          "Psychosis / Schizophrenia",
          "OCD",
          "PTSD",
          "Personality disorder",
          "Substance use",
          "Other",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.pastPsychiatricHistory.pastTreatmentResponse`,
        label: "Previous psychiatric treatment & response",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.pastPsychiatricHistory.lifetimeSuicidalHistory`,
        label: "Lifetime suicidal history",
        type: "select",
        options: ["None", "Ideation only", "Attempt(s)"],
      },
    ],
  },
  {
    title: "Social & Environmental Assessment",
    items: [
      {
        kind: "field",
        path: `${P}.socialEnvironmental.primaryCarerType`,
        label: "Primary carer",
        type: "select",
        options: [
          "Spouse / Partner",
          "Adult child",
          "Sibling",
          "Professional carer",
          "No identified carer",
          "Other",
        ],
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.primaryCarerTypeOther`,
        label: "Primary carer — other (please specify)",
        type: "text",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.carerHealthCapacity`,
        label: "Carer health & capacity",
        type: "select",
        options: [
          "Good",
          "Moderate — some limitations",
          "Poor — at risk of breakdown",
          "Carer has own health issues",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.supportNetwork`,
        label: "Support network (friends, community, religious)",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.financialSituation`,
        label: "Financial situation",
        type: "select",
        options: [
          "Adequate",
          "Pension / government support",
          "Financial stress",
          "Dependent on family",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.legalFinancialArrangements`,
        label: "Legal / financial arrangements in place",
        type: "multiselect",
        options: [
          "Will",
          "Power of Attorney — financial",
          "Power of Attorney — health",
          "None",
          "Unknown",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.homeSuitability`,
        label: "Home suitability",
        type: "select",
        options: [
          "Appropriate",
          "Stairs — difficulty",
          "Cluttered / fall hazard",
          "Inadequate sanitation",
          "No heating / cooling",
          "Not suitable — recommend change",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.homeSafetyAids`,
        label: "Home safety aids",
        type: "multiselect",
        options: [
          "None",
          "Grab rails",
          "Ramp",
          "Hospital bed",
          "Commode / bedpan",
          "Alarm / call system",
          "Other",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.communityServicesInPlace`,
        label: "Service Requirements",
        type: "multiselect",
        options: [
          "None",
          "Home nursing",
          "Meals on wheels",
          "Day care centre",
          "Physiotherapy",
          "Occupational therapy",
          "Palliative home care",
          "Other",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.drivingStatus`,
        label: "Driving status",
        type: "select",
        options: [
          "Never drove",
          "Stopped voluntarily",
          "Still driving",
          "Advised to stop — refused",
          "Licence revoked",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.socialEnvironmental.wanderingElopementRisk`,
        label: "Wandering / elopement risk",
        type: "select",
        options: [
          "None",
          "Low",
          "Moderate — supervision required",
          "High — secured environment needed",
        ],
      },
    ],
  },
];

export default geriatricConfig;
