import { EPISODE_PHASES, SUBSTANCE_PROFILE_ROWS } from "./Fields";

const P = "psychiatricFields";

const psychiatricConfig = [
  {
    title: "History of Present Illness",
    items: [
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.onsetAge`,
        label: "Date / Age at onset of current episode",
        type: "text",
      },
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.modeOfOnset`,
        label: "Mode of onset",
        type: "select",
        options: [
          "Acute (< 2 weeks)",
          "Subacute (2–4 weeks)",
          "Insidious (> 1 month)",
        ],
      },
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.precipitatingFactors`,
        label: "Precipitating factors",
        type: "multiselect",
        options: [
          "None identified",
          "Psychosocial stressor",
          "Substance use",
          "Medical illness",
          "Medication change",
          "Other",
        ],
      },
      {
        kind: "field",
        path: `${P}.pastIllness.substanceUseHistory`,
        label: "Substance Use History",
        type: "select",
        options: ["Yes", "No"],
      },
      {
        kind: "grid",
        path: `${P}.pastIllness.substanceUseTable`,
        title: "Substance Use Profile",
        showIf: {
          path: `${P}.pastIllness.substanceUseHistory`,
          equals: "Yes",
        },
        skipValidationWhen: {
          path: `${P}.pastIllness.substanceUseHistory`,
          equals: "No",
        },
        rowLabelKey: "substance",
        rowLabels: SUBSTANCE_PROFILE_ROWS,
        columns: [
          { key: "ageOfFirstUse", label: "Age of First Use", type: "text" },
          { key: "currentUse", label: "Current Use", type: "text" },
          { key: "frequency", label: "Frequency", type: "text" },
          { key: "quantityDose", label: "Quantity / Dose", type: "text" },
          {
            key: "route",
            label: "Route",
            type: "select",
            options: [
              "Oral",
              "Smoking / Inhalation",
              "Intravenous",
              "Intranasal",
              "Sublingual",
              "Other",
            ],
          },
          { key: "lastUse", label: "Last Use", type: "text" },
        ],
      },
      {
        kind: "field",
        path: `${P}.historyOfPresentIllness.onsetDurationProgress`,
        label: "Onset Duration & Progress",
        type: "textarea",
      },
   

      {
        kind: "field",
        path: `${P}.symptomDomains.affective`,
        label: "Affective symptoms",
        type: "multiselect",
        options: [
          "Depressed mood",
          "Anhedonia",
          "Elevated mood",
          "Irritability",
          "Emotional lability",
          "Anxiety",
          "Panic attacks",
          "Phobic avoidance",
          "OCD symptoms",
          "None",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.symptomDomains.psychotic`,
        label: "Psychotic symptoms",
        type: "multiselect",
        options: [
          "Auditory hallucinations",
          "Visual hallucinations",
          "Other hallucinations",
          "Persecutory delusions",
          "Grandiose delusions",
          "Referential ideas",
          "Thought insertion",
          "Thought withdrawal",
          "Thought broadcasting",
          "Passivity phenomena",
          "None",
        ],
      },
      {
        kind: "field",
        path: `${P}.symptomDomains.psychoticNotes`,
        label: "Psychotic symptoms — additional notes (optional)",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.symptomDomains.cognitive`,
        label: "Cognitive symptoms",
        type: "multiselect",
        options: [
          "Poor attention / concentration",
          "Memory impairment",
          "Disorientation",
          "Confusion",
          "Perplexity",
          "Intellectual decline",
          "None",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.symptomDomains.behavioural`,
        label: "Behavioural symptoms",
        type: "multiselect",
        options: [
          "Aggression / Violence",
          "Agitation",
          "Social withdrawal",
          "Wandering",
          "Self-neglect",
          "Disinhibition",
          "Stereotype / Mannerism",
          "Bizarre behaviour",
          "None",
        ],
      },
      {
        kind: "field",
        path: `${P}.symptomDomains.somaticNeurovegetative`,
        label: "Somatic / Neurovegetative",
        type: "multiselect",
        options: [
          "Sleep disturbance",
          "Appetite change",
          "Weight change",
          "Fatigue / Anergia",
          "Psychomotor change",
          "Somatic complaints",
          "Pain",
          "None",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.symptomDomains.suicidalitySelfHarm`,
        label: "Suicidality / Self-harm",
        type: "multiselect",
        options: [
          "Passive death wish",
          "Suicidal ideation",
          "Suicidal plan",
          "Suicidal intent",
          "Self-harm behaviour",
          "None",
        ],
      },
      {
        kind: "field",
        path: `${P}.suicidalSelfHarmHistory.mostSeriousAttemptDetails`,
        label: "Most serious attempt — method, lethality, intent",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.symptomDomains.substanceUseCurrentEpisode`,
        label: "Substance use (current episode)",
        type: "multiselect",
        options: [
          "Alcohol",
          "Opioids",
          "Cannabis",
          "Tobacco",
          "Benzodiazepines",
          "Other",
          "None",
        ],
      },

      {
        kind: "field",
        path: `${P}.functionalImpact.workOccupationalFunctioning`,
        label: "Work / Occupational functioning",
        type: "select",
        options: [
          "Intact",
          "Mildly impaired",
          "Moderately impaired",
          "Severely impaired",
          "Unable to work",
        ],
      },
      {
        kind: "field",
        path: `${P}.functionalImpact.socialInterpersonalFunctioning`,
        label: "Social / Interpersonal functioning",
        type: "select",
        options: [
          "Intact",
          "Mildly impaired",
          "Moderately impaired",
          "Severely impaired",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.functionalImpact.selfCareAdl`,
        label: "Self-care / ADL",
        type: "select",
        options: [
          "Intact",
          "Mildly impaired",
          "Moderately impaired",
          "Severely impaired",
        ],
      },
      {
        kind: "field",
        path: `${P}.functionalImpact.gafScore`,
        label: "GAF Score ( _ / 100)",
        type: "number",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.functionalImpact.gafSeverity`,
        label: "GAF Severity",
        type: "select",
        options: [
          "Mild (61-100)",
          "Moderate (51-60)",
          "Serious (41-50)",
          "Severe (21-40)",
          "Very Severe (1-20)",
        ],
        required: false,
      },
    ],
  },
  {
    title: "History of Past Illness",
    items: [
      {
        kind: "grid",
        path: `${P}.pastIllness.episodeTimeline`,
        title: "Psychiatric Episode Timeline",
        rowLabelKey: "episodePhase",
        rowLabels: EPISODE_PHASES,
        columns: [
          {
            key: "approxDateAge",
            label: "Approximate Date / Age",
            type: "text",
          },
          { key: "duration", label: "Duration", type: "text" },
          {
            key: "treatmentReceived",
            label: "Treatment Received",
            type: "text",
          },
        ],
      },
      {
        kind: "field",
        path: `${P}.pastIllness.totalHospitalisations`,
        label: "Total number of psychiatric hospitalisations",
        type: "number",
      },
      {
        kind: "field",
        path: `${P}.pastIllness.previousDiagnoses`,
        label: "Previous diagnoses given",
        type: "multiselect",
        options: [
          "None",
          "Schizophrenia / Psychosis",
          "Bipolar disorder",
          "MDD / Depressive disorder",
          "Anxiety disorder",
          "OCD",
          "PTSD",
          "Personality disorder",
          "Organic / Neurocognitive",
          "Substance use disorder",
          "Other",
        ],
      },
      {
        kind: "field",
        path: `${P}.pastIllness.bestPeriodOfFunctioning`,
        label: "Best period of functioning between episodes",
        type: "textarea",
        required: false,
      },

      {
        kind: "field",
        path: `${P}.pastTreatment.medicationsTried`,
        label: "Medications tried (drug, dose, duration, response)",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.pastTreatment.ect`,
        label: "ECT",
        type: "select",
        options: ["Never", "Given", "Recommended but refused"],
      },
      {
        kind: "field",
        path: `${P}.pastTreatment.psychotherapyType`,
        label: "Psychotherapy / Counselling",
        type: "multiselect",
        options: [
          "Never",
          "CBT",
          "DBT",
          "Supportive",
          "Psychodynamic",
          "Family therapy",
          "Other",
        ],
        required: false,
      },
      {
        kind: "field",
        path: `${P}.pastTreatment.responseToTreatment`,
        label: "Response to previous treatments",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.pastTreatment.reasonsForDiscontinuation`,
        label: "Reasons for discontinuation / non-compliance",
        type: "textarea",
        required: false,
      },

      {
        kind: "field",
        path: `${P}.suicidalSelfHarmHistory.homicidalIdeationViolence`,
        label: "Homicidal ideation / violence (lifetime)",
        type: "select",
        options: ["None", "Ideation only", "Threats", "Acts"],
      },
    ],
  },
  {
    title: "Psychosocial & Support Assessment",
    items: [
      {
        kind: "field",
        path: `${P}.psychosocialSupport.familySupport`,
        label: "Family support / atmosphere",
        type: "select",
        options: [
          "Supportive / cohesive",
          "Conflictual",
          "Neglectful",
          "Abusive",
          "Enmeshed",
          "Disengaged",
        ],
      },
      {
        kind: "field",
        path: `${P}.psychosocialSupport.significantRelationships`,
        label: "Significant relationships / peer support",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.psychosocialSupport.financialSituationDebts`,
        label: "Financial situation / debts",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.psychosocialSupport.leisureHobbiesProtectiveFactors`,
        label: "Leisure / hobbies / protective factors",
        type: "textarea",
        required: false,
      },
      {
        kind: "field",
        path: `${P}.psychosocialSupport.spiritualCulturalBeliefs`,
        label: "Spiritual / cultural beliefs",
        type: "textarea",
        required: false,
      },
    ],
  },
];

export default psychiatricConfig;
