export const DASHBOARD = "DASHBOARD";
export const REPORT = "REPORT";
export const FINANACE = "FINANACE";
export const PATIENT_ANALYTICS = "PATIENT_ANALYTICS";
export const LEAD_ANALYTICS = "LEAD_ANALYTICS";
export const OPD_ANALYTICS = "OPD_ANALYTICS";
