export const panssQuestions = [
  {
    id: "P1",
    question: {
      en: "DELUSIONS - Beliefs which are unfounded, unrealistic and idiosyncratic. ",
      hi: "भ्रम – ऐसे विश्वास जो निराधार, अवास्तविक और व्यक्तिविशिष्ट होते हैं।",
    },
    type: "mutiple",
    domain: "Positive",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Thought content expressed in the interview and its influence on social relations and behaviour.",
      hi: "साक्षात्कार में व्यक्त विचार-वस्तु और इसका सामाजिक संबंधों और व्यवहार पर प्रभाव।"
    }
  },
  {
    id: "P2",
    question: {
      en: "CONCEPTUAL DISORGANISATION - Disorganised process of thinking characterised by disruption of goal-directed sequencing, e.g. circumstantiality, loose associations, tangentiality, gross illogicality or thought block. ",
      hi: "संकल्पनात्मक अव्यवस्था – सोचने की अव्यवस्थित प्रक्रिया, जिसकी विशेषता है लक्ष्य-उन्मुख क्रम में बाधा आना। जैसे: अत्यधिक विस्तार, ढीले संबंध, विषयांतर, स्पष्ट तर्कहीनता या विचार अवरोध।",
    },
    type: "mutiple",
    domain: "Positive",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Cognitive-verbal processes observed during the course of interview.",
      hi: "साक्षात्कार के दौरान देखी गई संज्ञानात्मक-मौखिक प्रक्रियाएँ।"
    }
  },
  {
    id: "P3",
    question: {
      en: "HALLUCINATORY BEHAVIOUR - Verbal report or behaviour indicating perceptions which are not generated by external stimuli. These may occur in the auditory, visual, olfactory or somatic realms. ",
      hi: "भ्रमात्मक आचरण – ऐसा मौखिक विवरण या व्यवहार जो उन धारणाओं को दर्शाता है जो बाहरी उद्दीपन से उत्पन्न नहीं होतीं। यह श्रवण, दृष्टि, घ्राण या शारीरिक क्षेत्रों में हो सकता है।",
    },
    type: "mutiple",
    domain: "Positive",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Verbal report and physical manifestations during the course of interview as well as reports of behaviour by primary care workers or family.",
      hi: "साक्षात्कार के दौरान मौखिक रिपोर्ट और शारीरिक लक्षण, साथ ही इसे प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा रिपोर्ट किया गया व्यवहार।"
    }
  },
  {
    id: "P4",
    question: {
      en: "EXCITEMENT - Hyperactivity as reflected in accelerated motor behaviour, heightened responsivity to stimuli, hypervigilance or excessive mood lability. ",
      hi: "उत्तेजना – अत्यधिक सक्रियता, जो तीव्र गति वाले मोटर व्यवहार, उद्दीपनों के प्रति बढ़ी हुई प्रतिक्रिया, अत्यधिक सतर्कता या अत्यधिक मनोभाव परिवर्तन के रूप में प्रकट होती है।",
    },
    type: "mutiple",
    domain: "Positive",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Behavioural manifestations during the course of interview as well as reports of behaviour by primary care workers or family.",
      hi: "साक्षात्कार के दौरान प्रकट हुए व्यवहार और इसे प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा रिपोर्ट किया गया व्यवहार।"
    }
  },
  {
    id: "P5",
    question: {
      en: "GRANDIOSITY - Exaggerated self-opinion and unrealistic convictions of superiority, including delusions of extraordinary abilities, wealth, knowledge, fame, power and moral righteousness. ",
      hi: "महानता की भावना – आत्म-मूल्यांकन का अतिरंजित भाव और अवास्तविक श्रेष्ठता की धारणाएँ, जिनमें असाधारण क्षमताओं, धन, ज्ञान, प्रसिद्धि, शक्ति और नैतिक धार्मिकता के भ्रम शामिल होते हैं।",
    },
    type: "mutiple",
    domain: "Positive",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Thought content expressed in the interview and its influence on behaviour. ",
      hi: "साक्षात्कार में व्यक्त विचार-वस्तु और इसका व्यवहार पर प्रभाव।"
    }
  },
  {
    id: "P6",
    question: {
      en: "SUSPICIOUSNESS/PERSECUTION - Unrealistic or exaggerated ideas of persecution, as reflected in guardedness, ad distrustful attitude, suspicious hypervigilance or frank delusions that others mean harm. ",
      hi: "संदेह/उत्पीड़न भावना – उत्पीड़न से जुड़ी अवास्तविक या अतिरंजित धारणाएँ, जो सतर्क व्यवहार, अविश्वासी रवैया, संदेहपूर्ण अत्यधिक सतर्कता या स्पष्ट भ्रम के रूप में प्रकट होती हैं कि अन्य लोग नुकसान पहुँचाना चाहते हैं।",
    },
    type: "mutiple",
    domain: "Positive",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Thought content expressed in the interview and its influence on behaviour. ",
      hi: "साक्षात्कार में व्यक्त विचार-वस्तु और इसका व्यवहार पर प्रभाव।"
    }
  },
  {
    id: "P7",
    question: {
      en: "HOSTILITY - Verbal and nonverbal expressions of anger and resentment, including sarcasm, passive-aggressive behaviour, verbal abuse and assualtiveness. ",
      hi: "वैमनस्य – क्रोध और असंतोष की मौखिक और अमौखिक अभिव्यक्तियाँ, जिनमें व्यंग्य, निष्क्रिय-आक्रामक व्यवहार, मौखिक दुर्व्यवहार और आक्रामकता शामिल होती हैं।",
    },
    type: "mutiple",
    domain: "Positive",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Interpersonal behaviour observed during the interview and reports by primary care workers or family. ",
      hi: "साक्षात्कार के दौरान देखा गया अंतरव्यक्तिगत व्यवहार और इसे प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा रिपोर्ट किया गया।"
    }
  },

  {
    id: "N1",
    question: {
      en: "BLUNTED AFFECT - Diminished emotional responsiveness as characterised by a reduction in facial expression, modulation of feelings and communicative gestures. ",
      hi: "भावहीन प्रभाव – भावनात्मक प्रतिक्रिया में कमी, जो चेहरे के भाव, भावनाओं के अभिव्यंजन और संचारात्मक इशारों में कमी द्वारा प्रदर्शित होती है।",
    },
    type: "mutiple",
    domain: "Negative",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Observation of physical manifestations of affective tone and emotional responsiveness during the course of the interview. ",
      hi: "साक्षात्कार के दौरान भावनात्मक लहजे और भावनात्मक प्रतिक्रिया के शारीरिक लक्षणों का अवलोकन।"
    }
  },
  {
    id: "N2",
    question: {
      en: "EMOTIONAL WITHDRAWAL - Lack of interest in, involvement with, and affective commitment to life’s events.",
      hi: "भावनात्मक अलगाव – जीवन की घटनाओं में रुचि, भागीदारी और भावनात्मक प्रतिबद्धता की कमी।",
    },
    type: "mutiple",
    domain: "Negative",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Reports of functioning from primary care workers or family and observation of interpersonal behaviour during the course of the interview.",
      hi: "कार्यप्रणाली पर प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा दी गई रिपोर्ट और साक्षात्कार के दौरान देखा गया अंतरव्यक्तिगत व्यवहार।"
    }
  },
  {
    id: "N3",
    question: {
      en: "POOR RAPPORT - Lack of interpersonal empathy, openness in conversation and sense of closeness, interest or involvement with the interviewer. This is evidenced by interpersonal distancing and reduced verbal and nonverbal communication. ",
      hi: "खराब संवाद संबंध – अंतरव्यक्तिगत सहानुभूति, बातचीत में खुलापन और साक्षात्कारकर्ता के साथ निकटता, रुचि या सहभागिता की कमी। यह अंतरव्यक्तिगत दूरी और मौखिक तथा अमौखिक संचार में कमी से दिखाई देती है।",
    },
    type: "mutiple",
    domain: "Negative",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Interpersonal behaviour during the course of the interview.",
      hi: "साक्षात्कार के दौरान अंतरव्यक्तिगत व्यवहार।"
    }
  },
  {
    id: "N4",
    question: {
      en: "PASSIVE/APATHETIC SOCIAL WITHDRAWAL - Diminished interest  and initiative in social interactions due to passivity, apathy, anergy or avolition. This leads to reduced interpersonal involvements and neglect of activities of daily living.",
      hi: "निष्क्रिय/उदासीन सामाजिक अलगाव – निष्क्रियता, उदासीनता, ऊर्जा की कमी या इच्छा-हीनता के कारण सामाजिक संपर्क में रुचि और पहल में कमी। इससे अंतरव्यक्तिगत सहभागिता में कमी और दैनिक क्रियाओं की अनदेखी होती है।",
    },
    type: "mutiple",
    domain: "Negative",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Reports on social behaviour from primary care workers or family.",
      hi: "सामाजिक व्यवहार पर प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा दी गई रिपोर्ट।"
    }
  },
  {
    id: "N5",
    question: {
      en: "DIFFICULTY IN ABSTRACT THINKING - Impairment in the use of the abstract-symbolic mode of thinking, as evidenced by difficulty in classification, forming generalisations and proceeding beyond concrete or egocentric thinking in problem-solving tasks. ",
      hi: "सारात्मक सोच में कठिनाई – सारात्मक और प्रतीकात्मक सोच के उपयोग में बाधा, जो वर्गीकरण करने, सामान्यीकरण बनाने और समस्या समाधान में ठोस या आत्मकेंद्रित सोच से आगे बढ़ने में कठिनाई द्वारा प्रकट होती है।",
    },
    type: "mutiple",
    domain: "Negative",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Responses to questions on similarities and proverb interpretation, and use of concrete vs. abstract mode during the course of the interview.",
      hi: "साक्षात्कार के दौरान समानताओं और कहावतों की व्याख्या से संबंधित प्रश्नों के उत्तर, तथा ठोस और सारात्मक सोच के उपयोग का अवलोकन।"
    }
  },
  {
    id: "N6",
    question: {
      en: "LACK OF SPONTANEITY AND FLOW OF CONVERSATION  - Reduction in the normal flow  of communication associated with apathy, avolition, defensiveness or cognitive deficit. This is manifested by diminished fluidity and productivity of the verbal interactional process. ",
      hi: "बातचीत में स्वतःस्फूर्तता और प्रवाह की कमी – उदासीनता, इच्छा-हीनता, रक्षात्मकता या संज्ञानात्मक कमी से जुड़ी सामान्य संचार प्रवाह में कमी। यह मौखिक बातचीत की प्रवाहशीलता और उत्पादकता में कमी के रूप में प्रकट होती है।",
    },
    type: "mutiple",
    domain: "Negative",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Cognitive-verbal processes observed during the course of interview. ",
      hi: "साक्षात्कार के दौरान देखे गए संज्ञानात्मक-मौखिक प्रक्रियाएँ।"
    }
  },
  {
    id: "N7",
    question: {
      en: "STEREOTYPED THINKING - Decreased fluidity, spontaneity and flexibility of thinking, as evidenced in rigid, repetitious or barren thought content.",
      hi: "सांकेतिक/पारंपरिक सोच – सोच की प्रवाहशीलता, स्वतःस्फूर्तता और लचीलापन में कमी, जो कठोर, दोहरावदार या शुष्क विचार-वस्तु में दिखाई देती है।",
    },
    type: "mutiple",
    domain: "Negative",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Cognitive-verbal processes observed during the interview.",
      hi: "साक्षात्कार के दौरान देखे गए संज्ञानात्मक-मौखिक प्रक्रियाएँ।"
    }
  },

  {
    id: "G1",
    question: {
      en: "SOMATIC CONCERN - Physical complaints or beliefs about bodily illness or malfunctions. This may range from a vague sense of ill being to clear-cut delusions of catastrophic physical disease. ",
      hi: "शारीरिक चिंता – शारीरिक बीमारी या दोष के बारे में शिकायतें या विश्वास। यह हल्की अस्वस्थता की भावना से लेकर गंभीर शारीरिक बीमारी के स्पष्ट भ्रम तक हो सकता है।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Thought content expressed in the interview.",
      hi: "साक्षात्कार में व्यक्त विचार-वस्तु।"
    }
  },
  {
    id: "G2",
    question: {
      en: "ANXIETY - Subjective experience of nervousness, worry, apprehension or restlessness, ranging from excessive concern about the present or future to feelings of panic.",
      hi: "चिंता – बेचैनी, फिक्र, आशंका या बेचैनी का व्यक्तिपरक अनुभव, जो वर्तमान या भविष्य के प्रति अत्यधिक चिंता से लेकर आतंक की भावना तक हो सकता है।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Verbal report during the course of interview and corresponding physical manifestations.",
      hi: "साक्षात्कार के दौरान मौखिक रिपोर्ट और संबंधित शारीरिक लक्षण।"
    }
  },
  {
    id: "G3",
    question: {
      en: "GUILT FEELINGS - Sense of remorse or self-blame for real or imagined misdeeds in the past. ",
      hi: "अपराधबोध – अतीत में वास्तविक या कल्पित कृत्यों के लिए पछतावे या आत्म-दोष की भावना।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Verbal report of guilt feelings during the course of interview and the influence on attitudes and thoughts. ",
      hi: "साक्षात्कार के दौरान अपराधबोध की मौखिक रिपोर्ट और इसका दृष्टिगत प्रभाव विचारों और दृष्टिकोण पर।"
    }
  },
  {
    id: "G4",
    question: {
      en: "TENSION -Overt physical manifestations of fear, anxiety, and agitation, such as stiffness, tremor, profuse sweating and restlessness. ",
      hi: "तनाव – भय, चिंता और बेचैनी के स्पष्ट शारीरिक लक्षण, जैसे कठोरता, कंपकंपी, अधिक पसीना आना और बेचैनी।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Verbal report attesting to anxiety and thereupon the severity of physical manifestations of tension observed during the interview. ",
      hi: "उदासी की मौखिक रिपोर्ट और इसके आधार पर साक्षात्कार के दौरान देखे गए तनाव के शारीरिक लक्षणों की गंभीरता।"
    }
  },
  {
    id: "G5",
    question: {
      en: "MANNERISMS AND POSTURING – Unnatural movements or posture as characterised be an awkward, stilted, disorganised, or bizarre appearance. ",
      hi: "अद्भुत व्यवहार और मुद्राएँ – अस्वाभाविक गति या मुद्रा, जो अजीब, कठोर, अव्यवस्थित या असामान्य दिखावट द्वारा प्रकट होती हैं।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Observation of physical manifestations during the course of interview as well as reports from primary care workers or family. ",
      hi: "साक्षात्कार के दौरान शारीरिक लक्षणों का अवलोकन तथा इसे प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा रिपोर्ट किया गया।"
    }
  },
  {
    id: "G6",
    question: {
      en: "DEPRESSION - Feelings of sadness, discouragement, helplessness and pessimism.",
      hi: "अवसाद – उदासी, हतोत्साह, असहायता और निराशावाद की भावनाएँ।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Verbal report of depressed mood during the course of interview and its observed influence on attitude and behaviour. ",
      hi: "साक्षात्कार के दौरान उदास मनोवृत्ति की मौखिक रिपोर्ट और इसका दृष्टिगत प्रभाव व्यवहार और दृष्टिकोण पर।"
    }
  },
  {
    id: "G7",
    question: {
      en: "MOTOR RETARDATION – Reduction in motor activity as reflected in slowing or lessening or movements and speech, diminished responsiveness of stimuli, and reduced body tone. ",
      hi: "मोटर मंदता – गति और बोलने में धीमापन या कमी, उद्दीपनों के प्रति घटती प्रतिक्रिया और शरीर की टोन में कमी के रूप में मोटर गतिविधि में कमी।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Manifestations during the course of interview as well as reports by primary care workers as well as family.",
      hi: "साक्षात्कार के दौरान प्रकट होने वाले लक्षण तथा इसे प्राथमिक देखभाल कर्मचारियों और परिवार द्वारा रिपोर्ट किया गया।"
    }
  },
  {
    id: "G8",
    question: {
      en: " UNCOOPERATIVENESS - Active refusal to comply with the will of significant others, including the interviewer, hospital staff or family, which may be associated with distrust, defensiveness, stubbornness, negativism, rejection of authority, hostility or belligerence. ",
      hi: "असहयोगिता – महत्वपूर्ण अन्य लोगों जैसे साक्षात्कारकर्ता, अस्पताल कर्मियों या परिवार की इच्छाओं के पालन से सक्रिय इनकार, जो अविश्वास, रक्षात्मकता, जिद, नकारात्मकता, अधिकार का अस्वीकार, वैमनस्य या झगड़ालु प्रवृत्ति से जुड़ा हो सकता है।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Interpersonal behaviour observed during the course of the interview 0as well as reports by primary care workers or family. ",
      hi: "साक्षात्कार के दौरान देखा गया अंतरव्यक्तिगत व्यवहार तथा इसे प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा रिपोर्ट किया गया।"
    }
  },
  {
    id: "G9",
    question: {
      en: "UNUSUAL THOUGHT CONTENT - Thinking characterised by strange, fantastic or bizarre ideas, ranging from those which are remote or atypical to those which are distorted, illogical and patently absurd.",
      hi: "असामान्य विचार-वस्तु – ऐसी सोच जो अजीब, कल्पनाशील या असामान्य विचारों से भरी होती है, जो सामान्य से दूर या असामान्य से लेकर विकृत, तर्कहीन और स्पष्ट रूप से हास्यास्पद तक हो सकती है।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: " Thought content expressed during the course of interview. ",
      hi: "साक्षात्कार के दौरान व्यक्त विचार-वस्तु।"
    }
  },
  {
    id: "G10",
    question: {
      en: "DISORIENTATION - Lack of awareness of one’s relationship to the milieu, including persons, place and time, which may be due to confusion or withdrawal. ",
      hi: "विक्षिप्तता – अपने परिवेश, जिसमें व्यक्ति, स्थान और समय शामिल हैं, के साथ संबंध की जागरूकता की कमी, जो भ्रम या अलगाव के कारण हो सकती है।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Responses to interview questions on orientation.",
      hi: "साक्षात्कार के दौरान अभिविन्यास (ओरिएंटेशन) से संबंधित प्रश्नों के उत्तर।"
    }
  },
  {
    id: "G11",
    question: {
      en: "POOR ATTENTION - Failure in focused alertness manifested by poor concentration, distractibility from internal and external stimuli, and difficulty in harnessing, sustaining or shifting focus to new stimuli.",
      hi: "ध्यान की कमी – केंद्रित सतर्कता में असफलता, जो कमजोर एकाग्रता, आंतरिक और बाहरी उद्दीपनों से विचलित होना, और नए उद्दीपनों पर ध्यान केंद्रित करने, बनाए रखने या स्थानांतरित करने में कठिनाई द्वारा प्रकट होती है।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Manifestations during the course of interview.",
      hi: "साक्षात्कार के दौरान प्रकट होने वाले लक्षण।"
    }
  },
  {
    id: "G12",
    question: {
      en: "LACK OF JUDGEMENT AND INSIGHT - Impaired awareness or understanding of one’s own psychiatric condition and life situation. This is evidenced by failure to recognise past or present psychiatric illness or symptoms, denial of need for psychiatric hospitalisation or treatment, decisions characterised by poor anticipation or consequences, and unrealistic short-term and long-range planning.",
      hi: "निर्णय और अंतर्दृष्टि की कमी – अपनी मानसिक स्थिति और जीवन परिस्थितियों की समझ या जागरूकता में कमी। यह अतीत या वर्तमान मानसिक बीमारी या लक्षणों को न पहचानना, मानसिक अस्पताल में भर्ती या उपचार की आवश्यकता का इनकार, खराब परिणामों की भविष्यवाणी वाले निर्णय, और अवास्तविक अल्पकालिक और दीर्घकालिक योजनाओं द्वारा प्रकट होती है।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Thought content expressed during the interview.",
      hi: "साक्षात्कार के दौरान व्यक्त विचार-वस्तु।"
    }
  },
  {
    id: "G13",
    question: {
      en: "DISTURBANCE OF VOLITION – Disturbance in the wilful initiation, sustenance and control of one’s thoughts, behaviour, movements and speech. ",
      hi: "इच्छाशक्ति में विकार – अपने विचार, व्यवहार, गति और भाषण की स्वेच्छित शुरुआत, बनाए रखने और नियंत्रण में विकार।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Thought content and behaviour manifested in the course of interview.",
      hi: "साक्षात्कार के दौरान प्रकट हुए विचार-वस्तु और व्यवहार।"
    }
  },
  {
    id: "G14",
    question: {
      en: "POOR IMPULSE CONTROL – Disordered regulation and control of action on inner urges, resulting in sudden, unmodulated, arbitrary or misdirected discharge of tension and emotions without concern about consequences.",
      hi: "आवेग नियंत्रण में कमी – आंतरिक इच्छाओं पर क्रिया के नियमन और नियंत्रण में असामान्यता, जिसके परिणामस्वरूप तनाव और भावनाओं का अचानक, अनियंत्रित, मनमाना या गलत दिशा में प्रकट होना होता है, बिना परिणाम की परवाह किए।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Behaviour during the course of interview and reported by primary care workers or family.",
      hi: "साक्षात्कार के दौरान व्यवहार और इसे प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा रिपोर्ट किया गया।"
    }
  },
  {
    id: "G15",
    question: {
      en: "PREOCCUPATION - Absorption with internally generated thoughts and feelings and with autistic experiences to the detriment of reality orientation and adaptive behaviour. ",
      hi: "अधिक संलग्नता – आंतरिक रूप से उत्पन्न विचारों और भावनाओं तथा आत्मकेंद्रित अनुभवों में इतनी गहराई से लिप्त होना कि वास्तविकता की समझ और अनुकूल व्यवहार प्रभावित हो।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: "Interpersonal behaviour observed during the course of interview. ",
      hi: "अंतरव्यक्तिगत व्यवहार – साक्षात्कार के दौरान देखा गया व्यवहार।"
    }
  },
  {
    id: "G16",
    question: {
      en: "ACTIVE SOCIAL AVOIDANCE    - Diminished social involvement associated with unwarranted fear, hostility, or distrust. ",
      hi: "सक्रिय सामाजिक परहेज़ – अनुचित भय, वैमनस्य या अविश्वास के कारण सामाजिक सहभागिता में कमी।",
    },
    type: "mutiple",
    domain: "General",
    score: {
      Absent: 1,
      Minimal: 2,
      Mild: 3,
      Moderate: 4,
      "Moderate Severe": 5,
      Severe: 6,
      Extreme: 7,
    },
    guidance: {
      en: " Reports of social functioning primary care workers or family.",
      hi: "सामाजिक कार्यप्रणाली की रिपोर्ट – प्राथमिक देखभाल कर्मचारियों या परिवार द्वारा दी गई।"
    }
  },
];

export const calculateScores = (answers) => {
  const scores = {
    totalScore: 0,
    Positive: 0,
    Negative: 0,
    General: 0,
    Composite: 0,
  };

  for (const [questionId, answerValue] of Object.entries(answers)) {
    const question = panssQuestions.find((q) => q.id === questionId);
    if (question && question.score && question.domain) {
      const scoreValue = question.score[answerValue];

      if (scoreValue !== undefined) {
        const domainKey = question.domain;
        if (scores.hasOwnProperty(domainKey)) {
          scores[domainKey] += scoreValue;
          scores.totalScore += scoreValue;
        }
      }
    }
  }

  scores.Composite = scores.Positive - scores.Negative;

  return scores;
};

export const getInterpretationAndRecommendations = (subscaleScores) => {
  let severity = "";
  let interpretation = "";
  let recommendations = "";

  if (subscaleScores.totalScore > 110) {
    severity = "Very Severe";
  } else if (subscaleScores.totalScore >= 81) {
    severity = "Severe/Marked";
  } else if (subscaleScores.totalScore >= 60) {
    severity = "Moderate";
  } else {
    severity = "Mild or Remitted";
  }

  interpretation += `The patient presents with an overall symptom severity classified as ${severity} (Total PANSS Score: ${subscaleScores.totalScore}). This score indicates the current level of psychopathology and the need for clinical intervention.`;

  const P_prominence = subscaleScores.Positive > subscaleScores.Negative + 5;
  const N_prominence = subscaleScores.Negative > subscaleScores.Positive + 5;


  if (P_prominence && subscaleScores.Positive > 20) {
    interpretation += ` The profile is primarily characterized by Positive Symptoms (Score: ${subscaleScores.Positive}), suggesting high load of psychotic features such as delusions, hallucinations, and conceptual disorganization.`;
  } else if (N_prominence && subscaleScores.Negative > 20) {
    interpretation += ` The profile is dominated by Negative Symptoms (Score: ${subscaleScores.Negative}), indicating significant deficits in emotional range, social drive, and rapport. This profile is often associated with poorer functional outcomes.`;
  } else if (subscaleScores.Positive >= 15 && subscaleScores.Negative >= 15) {
    interpretation += ` The patient exhibits a Mixed Symptom Profile with both positive (Score: ${subscaleScores.Positive}) and negative (Score: ${subscaleScores.Negative}) symptoms being moderately elevated, requiring broad-spectrum treatment.`;
  } else {
    interpretation += ` Symptom levels are generally low across the core dimensions, suggesting a current state of **remission** or minimal residual symptoms (Positive Score: ${subscaleScores.Positive}, Negative Score: ${subscaleScores.Negative}).`;
  }

  interpretation += ` The General Psychopathology subscale score (${subscaleScores.General}) reflects associated symptoms such as anxiety, depression, and poor impulse control.`;


  if (severity === "Very Severe" || severity === "Severe/Marked") {
    recommendations += `Acute Management & Pharmacotherapy: Due to the ${severity.toUpperCase()} severity, immediate and intensive pharmacological intervention is critical. Consideration of hospitalization or intensive monitoring is recommended. The antipsychotic regimen should be optimized, potentially using higher doses or a combination, focusing on aggressive symptom reduction.`;
  } else if (severity === "Moderate") {
    recommendations += `Treatment Adjustment & Monitoring: The patient requires optimization of current pharmacological treatment. Psychoeducation and symptom-focused therapy (e.g., CBTp) should be introduced or intensified to manage current symptoms.`;
  } else {
    recommendations += `Maintenance & Functional Recovery: The primary focus should be on maintaining stability with the current medication at the lowest effective dose. Psychosocial rehabilitation**, cognitive remediation, and vocational training are paramount to enhance functional recovery and quality of life.`;
  }

  recommendations += `Specific Psychosocial Focus:
 Positive Symptoms Focus (if P > 20): Implement Cognitive Behavioral Therapy for Psychosis (CBTp).
 Negative Symptoms Focus (if N > 20): Implement Cognitive Remediation Therapy (CRT) and social skills training.
 General Symptoms Focus: Initiate supportive psychotherapy and stress management techniques to address mood and anxiety symptoms.`;
  return {
    interpretationText: interpretation.trim(),
    recommendationsText: recommendations.trim(),
    severity
  };
};

